# -*- coding: utf-8 -*-
"""fact.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jH0gDndQz7KR_sppxm3eSyg0IUEX2lGq
"""

import requests

# Get the current date
import datetime
today = datetime.date.today()
month = today.month
day = today.day

# Retrieve a random fact about the current date
fact_url = f"http://numbersapi.com/{month}/{day}/date"
fact_response = requests.get(fact_url)
fact = fact_response.text

# Retrieve the weather details for Nairobi, Kenya
weather_url = "https://wttr.in/Nairobi?format=%C\n%t\n"
weather_response = requests.get(weather_url)
weather = weather_response.text

# Print the fact and weather details
print("Random fact about today's date:")
print(fact)

print("Weather details for Nairobi, Kenya:")
print(weather)